name: flutter_application_todo_list
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  cupertino_icons: ^1.0.2
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.8.3
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
